import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/TopNavbar";
import Footer from "@/components/Footer";
import TopNavbar from "@/components/TopNavbar";
import MiddleNavbar from "@/components/MiddleNavbar";
import BottomNavbar from "@/components/BottomNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNavbar/>
        <MiddleNavbar/>
        <BottomNavbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
